config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView
from core import views
from core.forms import RegisterForm

admin.site.site_header = "Stacks Admin"
admin.site.site_title = "Stacks Admin"
admin.site.index_title = "Stacks innards"


urlpatterns = [
    path("", views.home, name="index"),
    path("status/<slug:status>", views.status, name="status"),
    # PWA goodies
    path(
        "sw.js",
        TemplateView.as_view(
            template_name="js/sw.js", content_type="application/javascript"
        ),
        name="sw",
    ),
    path("offline", TemplateView.as_view(template_name="offline.html"), name="offline"),
    # Logbook
    path("logbook", views.logbook, name="logbook"),
    # Book Imports
    # ------------
    path("import", views.import_books, name="import_books"),
    path("imports", views.imports, name="imports"),
    # Changelog
    # ---------
    path("changelog", views.changelog, name="changelog"),
    path("changelog/latest", views.changelog_latest, name="changelog_latest"),
    path("changelog/feed", views.ChangelogFeed(), name="changelog_feed"),
    # Book CRUD
    # ---------
    path("book/new", views.book_new, name="book_new"),  # C
    path("book/<int:pk>", views.book_detail, name="book_detail"),  # R
    path("book/<int:pk>/update", views.book_update, name="book_update"),  # U
    path("book/<int:pk>/delete", views.book_delete, name="book_delete"),  # D
    path("book/<int:pk>/archive", views.book_archive, name="book_archive"),
    path("book/<int:pk>/unarchive", views.book_unarchive, name="book_unarchive"),
    # Book Series
    # -----------
    path("series", views.series_list, name="series_list"),
    path("series/new", views.series_new, name="series_new"),  # C
    path("series/<int:pk>", views.series_detail, name="series_detail"),  # R
    path("series/<int:pk>/update", views.series_update, name="series_update"),  # U
    path("series/<int:pk>/delete", views.series_delete, name="series_delete"),  # D
    path("series/<int:pk>/add", views.series_add_book, name="series_add_book"),
    path("series/<int:pk>/remove", views.series_remove_book, name="series_remove_book"),
    # Book Search
    # -----------
    path("search", views.search, name="search"),
    path("ol", views.open_library_search, name="open_library_search"),
    # Authors
    # -------
    path("author/new", views.author_new, name="author_new"),  # C
    path("author/<int:pk>", views.author_detail, name="author_detail"),  # R
    path("author/<int:pk>/update", views.author_update, name="author_update"),  # U
    path("author/<int:pk>/delete", views.author_delete, name="author_delete"),  # D
    # Book Covers
    # -----------
    path("book/<int:pk>/cover/new", views.cover_new, name="cover_new"),
    path(
        "book/<int:pk>/cover/<int:cover_pk>/update",
        views.cover_update,
        name="cover_update",
    ),
    path(
        "book/<int:pk>/cover/<int:cover_pk>/delete",
        views.cover_delete,
        name="cover_delete",
    ),
    path(
        "book/<int:pk>/cover/<int:cover_pk>/order/<str:direction>",
        views.cover_order,
        name="cover_order",
    ),
    # Book Readings
    # -------------
    path("book/<int:pk>/reading/new", views.reading_new, name="reading_new"),
    path(
        "book/<int:pk>/reading/<int:reading_pk>/update",
        views.reading_update,
        name="reading_update",
    ),
    path(
        "book/<int:pk>/reading/<int:reading_pk>/delete",
        views.reading_delete,
        name="reading_delete",
    ),
    # Book Notes
    # ----------
    path("book/<int:pk>/note/new", views.note_new, name="note_new"),
    path(
        "book/<int:pk>/note/<int:note_pk>/update",
        views.note_update,
        name="note_update",
    ),
    path(
        "book/<int:pk>/note/<int:note_pk>/delete",
        views.note_delete,
        name="note_delete",
    ),
    # User settings
    path("settings", views.user_settings, name="settings"),
    # Boilerplate
    # -----------
    path("favicon.ico", views.favicon),
    # Redirect the old registration URL.
    path(
        "register/",
        RedirectView.as_view(pattern_name="django_registration_register"),
    ),
    # Redirect an authenticated user from the login page.
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),
    path(
        "accounts/register/complete/",
        views.registration_complete,
        name="django_registration_complete",
    ),
    path(
        "accounts/register/",
        views.RegistrationView.as_view(
            form_class=RegisterForm,
        ),
        name="django_registration_register",
    ),
    path(
        "accounts/activate/",
        views.ActivationView.as_view(),
        name="django_registration_activate",
    ),
    path(
        "account-verified/<int:user_id>",
        views.account_verified,
        name="account-verified",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
        path("404", TemplateView.as_view(template_name="404.html")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.forms.widgets import MultipleHiddenInput
from django.forms import modelformset_factory
from django_registration.forms import RegistrationForm
from .models import (
    User,
    Book,
    BookCover,
    BookReading,
    BookNote,
    Author,
    Series,
    SeriesBook,
)
from .fields import GroupedModelChoiceField


class RegisterForm(RegistrationForm):
    email = forms.EmailField()
    usable_password = None

    class Meta(RegistrationForm.Meta):
        model = User
        fields = ("email", "password1", "password2")


class ImportBooksForm(forms.Form):
    csv = forms.FileField(label="Then, upload the CSV file here")


class OpenLibrarySearchForm(forms.Form):
    everything = forms.CharField(label="All fields", required=False)
    title = forms.CharField(label="Title", required=False)
    author = forms.CharField(label="Author", required=False)

    def __init__(self, *args, autofocus=True, **kwargs):
        super().__init__(*args, **kwargs)
        self.autofocus = autofocus
        self.attrs = {"autofocus": True} if self.autofocus else {}
        self.fields["title"].widget.attrs.update(self.attrs)


class BookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields["author"].label = "Author(s)"
        self.fields["author"].queryset = Author.objects.filter(user=self.user)
        self.fields["location"].label = "Location(s)"
        self.fields["genre"].label = "Genre(s)"
        self.fields["type"] = GroupedModelChoiceField(
            queryset=self.fields["type"].queryset.order_by("parent", "name"),
            choices_groupby="parent",
            required=False,
        )

    class Meta:
        model = Book
        fields = (
            "title",
            "status",
            "author",
            "type",
            "genre",
            "published_year",
            "format",
            "location",
            "olid",
            "pages",
        )


class BookStatusForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BookStatusForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget = forms.HiddenInput()
        self.fields["author"].widget = MultipleHiddenInput()
        self.fields["format"].widget = MultipleHiddenInput()
        self.fields["location"].widget = MultipleHiddenInput()
        self.fields["genre"].widget = MultipleHiddenInput()

    class Meta:
        model = Book
        exclude = ("created_at", "updated_at", "status")


class BookReadingForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), required=False
    )
    rating = forms.IntegerField(
        min_value=1, max_value=5, required=False, help_text="1-5 stars"
    )

    class Meta:
        model = BookReading
        fields = ("finished", "start_date", "end_date", "rating", "review")


class BookCoverForm(forms.ModelForm):
    url = forms.URLField(
        required=False, label="URL", help_text="If you don't have a file"
    )
    image = forms.ImageField(required=False)  # make image field optional

    class Meta:
        model = BookCover
        fields = ("image", "url", "description")

    def __init__(self, *args, **kwargs):
        self.book = kwargs.pop("book", None)
        super(BookCoverForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        image = cleaned_data.get("image")
        url = cleaned_data.get("url")

        if not image and url:
            self.instance.book = self.book
            success = self.instance.save_cover_from_url(url)

            if not success:
                self.add_error("url", "Failed to save cover from URL")

        return cleaned_data


class BookNoteForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = BookNote
        exclude = ("book", "page", "percentage", "created_at", "updated_at")


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = (
            "name",
            "bio",
        )


class SeriesForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SeriesForm, self).__init__(*args, **kwargs)
        self.fields["title"].widget.attrs.update({"autofocus": True})

    class Meta:
        model = Series
        fields = (
            "title",
            "description",
        )


class SeriesBookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SeriesBookForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field != "order":
                self.fields[field].widget = forms.HiddenInput()

    class Meta:
        model = SeriesBook
        exclude = [
            "order_label",
        ]


SeriesBookFormSet = modelformset_factory(
    SeriesBook,
    form=SeriesBookForm,
    extra=0,
)


class SettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "email",
            "timezone",
        )

templates/author_detail.html
{% extends "base.html" %}
{% load markdown_extras %}

{% block title %}
  {{ author }}
{% endblock title %}

{% block body_tag %}class="author-detail"{% endblock body_tag %}

{% block content %}
  <header class="actions">
    <h1>{{ author }}</h1>
    <form action="{% url 'author_delete' author.pk %}" method="post">
      {% csrf_token %}
      <div class="inner">
        <div class="faux-form"><a class="svg edit" href="{% url 'author_update' author.pk %}">Edit</a></div>
        <div class="faux-form"><button class="svg delete" onclick="return confirm('Are you sure you want to delete this author?')">Delete</button></div>
      </div>
    </form>
  </header>

  {% if author.bio %}
    <article class="description">{{ author.bio|markdown }}</article>
  {% endif %}

  <ul>
    {% for book in books %}
      <li class="book">
        <div class="cover">
          <a href="{{ book.get_absolute_url }}">
            {% if book.covers.all %}
              {% with book.covers.all|first as cover %}
                <img src="{{ cover.thumbnail.url }}"
                  alt="{{ cover }}"
                  height="auto"
                  width="150"
                  title="{{ book }}">
              {% endwith %}
            {% endif %}
          </a>
        </div>
        <div class="title" title="{{ book }}">{{ book }}</div>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

templates/author_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if action == 'new' %}
    Add a new author
    {% else %}
    Editing {{ author }}
    {% endif %}
{% endblock title %}

{% block body_tag %}class="form-page"{% endblock body_tag %}


{% block content %}
  <header>
    <h1>
      {% if action == 'new' %}
        Add a new author
      {% else %}
        Editing <a href="{{ author.get_absolute_url }}">{{ author }}</a>
      {% endif %}
    </h1>
  </header>

  <form method="post">
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
        <div>
          {{ field.as_field_group }}
        </div>
      {% endfor %}
    </fieldset>
    <button type="submit">Save</button>
  </form>
{% endblock content %}

templates/base.html
{% load static django_htmx %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="TBR tracking for tightly wound people">
    <link rel="apple-touch-icon" sizes="300x300" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="alternate" type="application/rss+xml" title="RSS Feed for the Changelog" href="{% url 'changelog_feed' %}">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="rgba(1, 170, 255)">
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="rgb(19, 23, 31)">
    {% url 'index' as index_url %}
    {% url 'book_new' as book_new_url %}
    {% url 'open_library_search' as ol_url %}
    <title>{% block title %}{% endblock title %}{% if request.path != index_url %} / {% endif %}Stacks.</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script defer src="{% static 'js/vendor/htmx.min.js' %}"></script>
    <script defer src="{% static 'js/vendor/htmx-alpine-morph.min.js' %}"></script>
    <script defer src="{% static 'js/vendor/alpinejs-sort.min.js' %}"></script>
    <script defer src="{% static 'js/vendor/alpinejs-morph.min.js' %}"></script>
    <script defer src="{% static 'js/vendor/alpinejs.min.js' %}"></script>
    {% block head_src %}{% endblock head_src %}
  </head>

  <body {% block body_tag %}{% endblock body_tag %}
    {% if request.path != book_new_url and user.is_authenticated %}
      x-data="{
        close() {
          $refs.addBook.close();
        },
        closeFromEvent(event) {
          if (event.currentTarget === event.target) {
            $refs.addBook.close();
          }
        },
      }"
    {% endif %}
  >
    <header class="container">
      {% if user.is_authenticated %}
        <nav class="main">
          <ul>
            <li>
              <div class="faux-form"><a class="svg stack" href="{% block stack_link %}{% url 'status' 'reading' %}{% endblock stack_link %}">Stacks</a></div>
            </li>
          </ul>

          <div class="desktop-search">
            {% include "components/search-form.html" %}
          </div>

          <ul>
            {% if user.is_superuser %}
              <li>
                <div class="faux-form">
                  <a class="svg admin" href="{% url 'admin:index' %}">Admin</a>
                </div>
              </li>
            {% endif %}

            {% url "logbook" as logbook_url %}
            <li{% if request.path == logbook_url %} class="active"{% endif %}>
              <div class="faux-form">
                <a{% if request.path == logbook_url %} aria-current="page"{% endif %} class="svg logbook" href="{% url 'logbook' %}"></a>
              </div>
            </li>

            {% url "series_list" as series_url %}
            <li{% if request.path == series_url %} class="active"{% endif %}>
              <div class="faux-form">
                <a{% if request.path == series_url %} aria-current="page"{% endif %} class="svg series" href="{% url 'series_list' %}">Series</a>
              </div>
            </li>
            {% url 'import_books' as import_url %}
            <li{% if request.path == import_url %} class="active"{% endif %}>
              <div class="faux-form"><a{% if request.path == import_url %} aria-current="page"{% endif %} class="svg import" href="{% url 'import_books' %}">Import</a></div>
            </li>
            {% url "changelog" as changelog_url %}
            <li{% if request.path == changelog_url %} class="active"{% endif %}>
              <div class="faux-form">
                <a{% if request.path == changelog_url %} aria-current="page"{% endif %} class="svg newspaper" href="{% url 'changelog' %}">Changelog</a>
                <div class="badge changelog-badge hidden"></div>
              </div>
            </li>
            {% url 'settings' as settings_url %}
            <li{% if request.path == settings_url %} class="active"{% endif %}>
              <div class="faux-form"><a{% if request.path == settings_url %} aria-current="page"{% endif %} class="svg settings" href="{% url 'settings' %}">Settings</a></div>
            </li>
            <li class="log-out">
              <form method="post" action="{% url 'logout' %}" onsubmit="return confirm('Do you want to log out?')">
                {% csrf_token %}
                <button class="svg log-out">
                  Log out
                </button>
            </form>
            </li>
          </ul>
        </nav>

        <div class="mobile-search">
          {% include "components/search-form.html" %}
        </div>
      {% endif %}
      {% block header %}
      {% endblock header %}

      {% if messages and 'status' not in request.path %}
        {% include "components/messages.html" %}
      {% endif %}
      <div class="offline messages">
        <ul>
          <li class="error">You’re offline! Some things are not going to work, but you should still be able to browse your books.</li>
        </ul>
      </div>
    </header>
    <main class="container">
      {% block content %}
      {% endblock content %}

      {% if request.path != book_new_url and request.path != ol_url and user.is_authenticated %}
        <div class="persistent-add">
          <a class="svg add-item-solid" href="{% url 'book_new' %}" @click.prevent="$refs.addBook.showModal()">Add a book</a>
          {% include "components/add-book-modal.html" %}
        </div>
      {% endif %}
    </main>
    <footer class="container">
      {% block footer %}
      {% endblock footer %}

      {% if user.is_authenticated %}
        <div class="support">
          <div class="faux-form ko-fi" data-tooltip="Support Book Stacks on Ko-fi" data-placement="right">
            <a class="svg heart-pulse" target="_blank" href="https://ko-fi.com/piepworks">💚</a>
          </div>
          <div class="faux-form" data-tooltip="Give feedback" data-placement="right">
            <a class="svg megaphone" data-canny-link href="https://piepworks.canny.io/bookstacks" title="Give feedback">
              Give feedback
            </a>
          </div>
        </div>
      {% endif %}

      <div class="copyright">Copyright © {% now "Y" %} <a href="https://piep.works">Piepworks LLC</a>. All rights reserved.</div>
    </footer>

    {% if not debug %}
      <script>{% include "js/sw-setup.js" %}</script>
    {% endif %}

    {% if user.is_authenticated %}
      <script>
        {% include "js/main.js" %}
      </script>

      {% if not debug %}
        <!-- Download Canny SDK -->
        <script>!function(w,d,i,s){function l(){if(!d.getElementById(i)){var f=d.getElementsByTagName(s)[0],e=d.createElement(s);e.type="text/javascript",e.async=!0,e.src="https://canny.io/sdk.js",f.parentNode.insertBefore(e,f)}}if("function"!=typeof w.Canny){var c=function(){c.q.push(arguments)};c.q=[],w.Canny=c,"complete"===d.readyState?l():w.attachEvent?w.attachEvent("onload",l):w.addEventListener("load",l,!1)}}(window,document,"canny-jssdk","script");</script>

        <!-- Use the Canny SDK to identify the current user of your website -->
        <script>
        Canny('identify', {
          appID: '6484a6e445e95c0961e5e44e',
          user: {
            email: '{{ user.email }}',
            name: '{{ user.email }}'.split('@')[0],
            id: '{{ user.id }}',
            customFields: {
              url: '{{ request.build_absolute_uri }}',
            }
          },
        });
        </script>
      {% endif %}
    {% endif %}

    {% django_htmx_script %}
    {% block page_js %}{% endblock page_js %}
  </body>
</html>

templates/book_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if action == 'new' %}
    Add a new book
    {% else %}
    Editing {{ book }}
    {% endif %}
{% endblock title %}

{% block head_src %}
  <link href="{% static 'css/vendor/tom-select.css' %}" rel="stylesheet">
  <script src="{% static 'js/vendor/tom-select.complete.min.js' %}"></script>
{% endblock head_src %}

{% block body_tag %}class="form-page"{% endblock body_tag %}

{% block stack_link %}{% if action != 'new' %}{% url 'status' book.status %}{% else %}{{ block.super }}{% endif %}{% endblock stack_link %}

{% block content %}
  <header>
    <h1>
      {% if action == 'new' %}
        Add a new book
      {% else %}
        Editing <a href="{{ book.get_absolute_url }}">{{ book }}</a>
      {% endif %}
    </h1>
  </header>

  {% if action == 'new' and cover != '' %}
    <section class="covers">
      <div>
        <img width="200"
            height="auto"
            alt="New cover"
            src="{{ cover }}">
      </div>
    </section>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <fieldset>
      {% if cover != '' %}
        <input type="hidden" name="cover" value="{{ cover }}">
      {% endif %}
      <input type="hidden" name="olid"{% if olid != '' %} value="{{ olid }}"{% endif %}>
      {% for field in form %}
        <div>
          {{ field.as_field_group }}
        </div>
      {% endfor %}
    </fieldset>
    <button type="submit">Save</button>
  </form>
{% endblock content %}

{% block page_js %}
<script>
  new TomSelect('#id_format', {
    plugins: {
      remove_button:{
        title:'Remove this item',
      }
    },
    closeAfterSelect: true,
  });

  new TomSelect('#id_location', {
    plugins: {
      remove_button:{
        title:'Remove this item',
      }
    },
    closeAfterSelect: true,
  });

  new TomSelect('#id_genre', {
    plugins: {
      remove_button:{
        title:'Remove this item',
      }
    },
    closeAfterSelect: true,
  });

  new TomSelect('#id_author', {
    create: function(input, callback) {
      // Get CSRF token
      const csrftoken = document.cookie.split('; ').find(row => row.startsWith('csrftoken')).split('=')[1];

      // Gather necessary data
      const authorData = {
        name: input, // assuming the input is the author's name
        // add other necessary data
      };

      // Send POST request
      fetch("{% url 'author_new' %}", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": csrftoken,
        },
        body: JSON.stringify(authorData),
      })
        .then((response) => {
          if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
          }
          return response.json();
        })
        .then((data) => {
          // Call the callback function with the new option
          callback({
            value: data.id,
            text: input
          });
        })
        .catch((error) => {
          console.error('There has been a problem with your fetch operation:', error);
        });
    },
    createOnBlur: true,
    closeAfterSelect: true,
    plugins: {
      remove_button:{
        title:'Remove this item',
      }
    },
  });
</script>
{% endblock page_js %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block body_tag %}class="home"{% endblock body_tag %}

{% block content %}
  <header>
    <div class="svg stack">Book Stacks icon</div>
    <h1>Stacks.</h1>
  </header>

  <div>
    <a href="{% url 'login' %}">Log in</a> or <a href="{% url 'django_registration_register' %}">create a free account</a>
  </div>

  <div class="intro">
    <p>Keep track of what you are reading, what you want to read, and what you've finished.</p>
    <p>Not a social network.</p>
    <div class="faux-form">
      <a class="svg github" href="https://github.com/piepworks/stacks">View source on GitHub</a>
    </div>
  </div>

  <div class="screenshots">
    <img loading="lazy" class="dark" src="{% static 'img/mobile-dark.png' %}" alt="Mobile screenshot (dark)" width="300" height="578.5">
    <img loading="lazy" class="light" src="{% static 'img/mobile-light.png' %}" alt="Mobile screenshot (light)" width="300" height="578.5">
    <img loading="lazy" class="dark" src="{% static 'img/desktop-dark.png' %}" alt="Desktop screenshot (dark)" width="600" height="453.5">
    <img loading="lazy" class="light" src="{% static 'img/desktop-light.png' %}" alt="Desktop screenshot (light)" width="600" height="453.5">
  </div>

{% endblock content %}

templates/import_books.html
{% extends "base.html" %}

{% block title %}Import Books{% endblock title %}

{% block content %}
  <header>
    <h1>Import your books from Goodreads or The StoryGraph</h1>
  </header>

  <p>First, export your library:</p>

  <ul>
    <li><a href="https://www.goodreads.com/review/import">Goodreads</a></li>
    <li><a href="https://app.thestorygraph.com/user-export">The StoryGraph</a></li>
  </ul>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      {{ form.csv.as_field_group }}
    </div>
    <input type="submit" value="Import">
  </form>
{% endblock content %}

templates/logbook.html
{% extends "base.html" %}
{% load status_display get_book %}

{% block title %}Logbook{% endblock title %}
{% block body_tag %}class="logbook"{% endblock body_tag %}

{% block content %}
  <header>
    <h1>Logbook</h1>
  </header>

  {% if page_obj.number == 1 %}
    <article class="description">Here’s what your books have been up to…</article>
  {% endif %}

  {% include "components/logbook-list.html" %}
{% endblock content %}

templates/ol_search.html
{% extends "base.html" %}

{% block title %}Choose a book{% endblock title %}

{% block body_tag %}class="ol-results"{% endblock body_tag %}

{% block content %}
  {% if local_results %}
    <h1>It looks like you may already have this book:</h1>
    <ul>
      {% for book in local_results %}
        <li class="book">
          {% include "components/book-list-item.html" %}
        </li>
      {% endfor %}
    </ul>

    <h2>No? Then check out these search results:</h2>
  {% else %}
    <h1>Search results</h1>
  {% endif %}

  <h2>Choose a cover</h2>

  <main>
    <p><a href="{% url 'book_new' %}">Skip this (no auto-populated fields)</a></p>

    <ul>
      {% for result in results %}
        <li class="book">
          <div class="cover">
            <a href="{% url 'book_new' %}?olid={{ result.olid }}&cover={{ result.cover }}&authors={{ result.authors_string }}&title={{ result.title }}&year={{ result.published }}&pages={{ result.pages }}{% if status %}&status={{ status }}{% endif %}">
              <div class="img-wrapper"><img src="{{ result.cover }}" alt="Cover of {{ result.title }}" width="300" height="auto"></div>
              <div class="image-spinner">
                <div aria-busy="true"></div>
              </div>
            </a>
          </div>
          <div class="title" title="{{ result.title }}">{{ result.title }}</div>
        </li>
      {% endfor %}
    </ul>

    <h3>Search again</h3>
    {% include "components/ol-search-form.html" %}
  </main>
{% endblock content %}

templates/placeholder.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Blaze.horse — Django Starter Kit
{% endblock title %}

{% block content %}
  <header>
    <div class="icon">
      <img src="{% static 'img/seahorse.svg' %}"
           height="200"
           width="200"
           alt="Seahorse icon">
    </div>
    <h1>Blaze.horse — Django Starter Kit</h1>
  </header>

  {% if request.user.is_authenticated %}
    <p>You’re logged in as {{ request.user }}!</p>
    <p>
      Now you can see <a href="{% url 'private-page' %}">the private page</a>.
    </p>
    <form method="post" action="{% url 'logout' %}">
      {% csrf_token %}
      <button>Log out</button>
    </form>
  {% else %}
    <p>
      <a href="{% url 'login' %}">Log in</a>
    </p>
  {% endif %}
{% endblock content %}

templates/series_list.html
{% extends "base.html" %}

{% block title %}Series{% endblock title %}

{% block body_tag %}class="series-list"{% endblock body_tag %}

{% block content %}
  <header class="actions-inline">
    <div>
      <h1>Series</h1>
      <div class="faux-form"><a class="svg add-item" href="{% url 'series_new' %}">add another</a></div>
    </div>
  </header>

  <ul>
    {% for s in series %}
      <li>
        <a href="{{ s.get_absolute_url }}">{{ s.title }}</a>
        <span class="subdued">{{ s.books.count }}</span>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}