config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView
from core import views
from core.forms import RegisterForm

admin.site.site_header = "Stacks Admin"
admin.site.site_title = "Stacks Admin"
admin.site.index_title = "Stacks innards"


urlpatterns = [
    path("", views.home, name="index"),
    path("status/<slug:status>", views.status, name="status"),
    # PWA goodies
    path(
        "sw.js",
        TemplateView.as_view(
            template_name="js/sw.js", content_type="application/javascript"
        ),
        name="sw",
    ),
    path("offline", TemplateView.as_view(template_name="offline.html"), name="offline"),
    # Logbook
    path("logbook", views.logbook, name="logbook"),
    # Book Imports
    # ------------
    path("import", views.import_books, name="import_books"),
    path("imports", views.imports, name="imports"),
    # Changelog
    # ---------
    path("changelog", views.changelog, name="changelog"),
    path("changelog/latest", views.changelog_latest, name="changelog_latest"),
    path("changelog/feed", views.ChangelogFeed(), name="changelog_feed"),
    # Book CRUD
    # ---------
    path("book/new", views.book_new, name="book_new"),  # C
    path("book/<int:pk>", views.book_detail, name="book_detail"),  # R
    path("book/<int:pk>/update", views.book_update, name="book_update"),  # U
    path("book/<int:pk>/delete", views.book_delete, name="book_delete"),  # D
    path("book/<int:pk>/archive", views.book_archive, name="book_archive"),
    path("book/<int:pk>/unarchive", views.book_unarchive, name="book_unarchive"),
    # Book Series
    # -----------
    path("series", views.series_list, name="series_list"),
    path("series/new", views.series_new, name="series_new"),  # C
    path("series/<int:pk>", views.series_detail, name="series_detail"),  # R
    path("series/<int:pk>/update", views.series_update, name="series_update"),  # U
    path("series/<int:pk>/delete", views.series_delete, name="series_delete"),  # D
    path("series/<int:pk>/add", views.series_add_book, name="series_add_book"),
    path("series/<int:pk>/remove", views.series_remove_book, name="series_remove_book"),
    # Book Search
    # -----------
    path("search", views.search, name="search"),
    path("ol", views.open_library_search, name="open_library_search"),
    # Authors
    # -------
    path("author/new", views.author_new, name="author_new"),  # C
    path("author/<int:pk>", views.author_detail, name="author_detail"),  # R
    path("author/<int:pk>/update", views.author_update, name="author_update"),  # U
    path("author/<int:pk>/delete", views.author_delete, name="author_delete"),  # D
    # Book Covers
    # -----------
    path("book/<int:pk>/cover/new", views.cover_new, name="cover_new"),
    path(
        "book/<int:pk>/cover/<int:cover_pk>/update",
        views.cover_update,
        name="cover_update",
    ),
    path(
        "book/<int:pk>/cover/<int:cover_pk>/delete",
        views.cover_delete,
        name="cover_delete",
    ),
    path(
        "book/<int:pk>/cover/<int:cover_pk>/order/<str:direction>",
        views.cover_order,
        name="cover_order",
    ),
    # Book Readings
    # -------------
    path("book/<int:pk>/reading/new", views.reading_new, name="reading_new"),
    path(
        "book/<int:pk>/reading/<int:reading_pk>/update",
        views.reading_update,
        name="reading_update",
    ),
    path(
        "book/<int:pk>/reading/<int:reading_pk>/delete",
        views.reading_delete,
        name="reading_delete",
    ),
    # Book Notes
    # ----------
    path("book/<int:pk>/note/new", views.note_new, name="note_new"),
    path(
        "book/<int:pk>/note/<int:note_pk>/update",
        views.note_update,
        name="note_update",
    ),
    path(
        "book/<int:pk>/note/<int:note_pk>/delete",
        views.note_delete,
        name="note_delete",
    ),
    # User settings
    path("settings", views.user_settings, name="settings"),
    # Boilerplate
    # -----------
    path("favicon.ico", views.favicon),
    # Redirect the old registration URL.
    path(
        "register/",
        RedirectView.as_view(pattern_name="django_registration_register"),
    ),
    # Redirect an authenticated user from the login page.
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),
    path(
        "accounts/register/complete/",
        views.registration_complete,
        name="django_registration_complete",
    ),
    path(
        "accounts/register/",
        views.RegistrationView.as_view(
            form_class=RegisterForm,
        ),
        name="django_registration_register",
    ),
    path(
        "accounts/activate/",
        views.ActivationView.as_view(),
        name="django_registration_activate",
    ),
    path(
        "account-verified/<int:user_id>",
        views.account_verified,
        name="account-verified",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
        path("404", TemplateView.as_view(template_name="404.html")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import os
import requests
import datetime
import pillow_avif  # noqa: F401 (ignore "unused import" error)
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from django.template.defaultfilters import date
from django.core.files.temp import NamedTemporaryFile
from django.core.files import File
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.conf import settings
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
from core.image_helpers import rename_image, resize_image
from ordered_model.models import OrderedModel


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(_("email address"), unique=True)
    timezone = models.CharField(
        max_length=40,
        blank=True,
        choices=settings.TIME_ZONES,
        default=settings.TIME_ZONE,
    )

    # Add more fields here.

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class Changelog(models.Model):
    date = models.DateField(default=datetime.date.today)
    summary = models.CharField(max_length=100)
    details = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Changelog Entry"
        verbose_name_plural = "Changelog Entries"

    def __str__(self):
        return f"Changes for {self.date}"


class Author(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="authors")
    bio = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (("user", "name"),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("author_detail", args=(self.pk,))

    @property
    def book_count(self):
        return (
            Book.objects.filter(
                author=self,
                user=self.user,
            )
            .exclude(archived=True)
            .count()
        )


class BookFormat(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class BookType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True)
    description = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.parent:
            return f"{self.parent.name} / {self.name}"
        return self.name


class BookGenre(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True)
    description = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["parent__name", "name"]

    def __str__(self):
        if self.parent:
            return f"{self.parent.name} / {self.name}"
        return self.name


class BookLocation(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books")
    author = models.ManyToManyField(Author, blank=True)
    published_year = models.IntegerField(blank=True, null=True)
    status = models.CharField(
        max_length=20,
        choices=[
            ("wishlist", "Wishlist"),
            ("backlog", "Backlog"),
            ("to-read", "To Read"),
            ("reading", "Reading"),
            ("finished", "Finished"),
            ("dnf", "Did Not Finish"),
        ],
    )
    type = models.ForeignKey(
        BookType,
        on_delete=models.SET_NULL,
        related_name="books",
        null=True,
        blank=True,
    )
    genre = models.ManyToManyField(
        BookGenre,
        related_name="books",
        help_text="Choose as many as you like",
        blank=True,
    )
    format = models.ManyToManyField(
        BookFormat,
        related_name="books",
        help_text="Choose as many as you have",
        blank=True,
    )
    location = models.ManyToManyField(
        BookLocation,
        related_name="books",
        help_text="For digital or audio books, choose the device or platform",
        blank=True,
    )
    archived = models.BooleanField(default=False)
    olid = models.CharField(max_length=100, blank=True, verbose_name="Open Library ID")
    pages = models.PositiveSmallIntegerField(blank=True, null=True)
    imported = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            UniqueConstraint(
                "user",
                Lower("title"),
                name="user_title_unique",
            )
        ]

    def __str__(self):
        if self.archived:
            return f"{self.title} (Archived)"
        return self.title

    def save(self, *args, **kwargs):
        new = not self.pk

        if self.pk:
            old_status = Book.objects.get(pk=self.pk).status
            new_status = self.status

            if old_status != new_status:
                # Add a BookReading with the current date as a start date.
                if new_status == "reading":
                    BookReading.objects.create(
                        book=self, start_date=datetime.date.today()
                    )

                # Add the current date as an `end_date` to the most recent BookReading (if any) and mark it `finished`.
                elif new_status == "finished":
                    reading = (
                        BookReading.objects.filter(book=self, end_date=None)
                        .order_by("-start_date")
                        .first()
                    )
                    if reading:
                        reading.end_date = datetime.date.today()
                        reading.finished = True
                        reading.save()

                # Add an `end_date` to the latest BookReading (if any), but don't mark it `finished`.
                elif old_status == "reading" and (
                    new_status == "to-read"
                    or new_status == "backlog"
                    or new_status == "wishlist"
                ):
                    reading = (
                        BookReading.objects.filter(book=self, end_date=None)
                        .order_by("-start_date")
                        .first()
                    )
                    if reading:
                        reading.end_date = datetime.date.today()
                        reading.save()

                # Add an `end_date` to the latest BookReading (if any), but don't mark it `finished`.
                elif new_status == "dnf":
                    reading = (
                        BookReading.objects.filter(book=self, end_date=None)
                        .order_by("-start_date")
                        .first()
                    )
                    if reading:
                        reading.end_date = datetime.date.today()
                        reading.save()

        super().save(*args, **kwargs)

        if new and self.status == "reading":
            BookReading.objects.create(book=self, start_date=datetime.date.today())

    def get_absolute_url(self):

templates/components/add-book-modal.html
<dialog @click="closeFromEvent(event)" x-ref="addBook" id="addBook">
  <article>
    <header>
      <button aria-label="Close"
              rel="prev"
              @click="close()"></button>
      <p><b>Search to add a book{% if status %}{% endif %}</b></p>
      <p>or <a href="{% url 'book_new' %}{% if status %}?status={{ status.slug }}{% endif %}">add manually</a></p>
    </header>
    {% include "components/ol-search-form.html" with form=open_library_search_form %}
  </article>
</dialog>

templates/components/book-filters.html
{% load get_item filter_matches_any %}
<form
  id="filters"
  x-show="openFilters"
  method="get"
  action="{% url 'status' status.slug %}"
  hx-get="{% url 'status' status.slug %}"
  hx-trigger="change"
  x-transition>
  <dl class="filters">
    <div>
      <dt>Types</dt>
      <dd>
        <div>
          <label>
            <input type="radio" name="type" value="all" {% if filter_queries.type %}checked{% endif %}>
            All
          </label>
        </div>

        {% for type in types %}
          {% if not type.parent %}
            {% if filter_counts.type|get_item:type.slug|get_item:'count' > 0 %}
              {% filter_matches_any type "type" filter_queries as is_selected %}
              <div{% if is_selected %} class="selected"{% endif %}>
                <label class="parent">
                  <input type="radio" name="type" value="{{ type.slug }}" {% if type.slug == filter_queries.type %}checked{% endif %}>
                  {{ type.name }}
                  ({{ filter_counts.type|get_item:type.slug|get_item:'count' }})
                </label>
                {% if type.has_sub_type %}
                  <div class="sub-filters">
                    {% for sub_type in types %}
                      {% if sub_type.parent == type %}
                        {% if filter_counts.type|get_item:type.slug|get_item:'sub_items'|get_item:sub_type.slug > 0 %}
                          <label>
                            <input type="radio" name="type" value="{{ sub_type.slug }}" {% if sub_type.slug == filter_queries.type %}checked{% endif %}>
                            {{ sub_type.name }}
                            ({{ filter_counts.type|get_item:type.slug|get_item:'sub_items'|get_item:sub_type.slug }})
                          </label>
                        {% endif %}
                      {% endif %}
                    {% endfor %}
                  </div>{# / Sub type #}
                {% endif %}
              </div>{# / Parent type #}
            {% endif %}
          {% endif %}
        {% endfor %}
      </dd>
    </div>
    <div>
      <dt>Genres</dt>
      <dd>
        <div>
          <label>
            <input type="radio" name="genre" value="all" {% if filter_queries.genre == 'all' %}checked{% endif %}>
            All
          </label>
        </div>
        {% for genre in genres %}
          {% if not genre.parent %}
            {% if filter_counts.genre|get_item:genre.slug|get_item:'count' > 0 %}
              {% filter_matches_any genre "genre" filter_queries as is_selected %}
              <div{% if is_selected %} class="selected"{% endif %}>
                <label class="parent">
                  <input type="radio" name="genre" value="{{ genre.slug }}" {% if genre.slug == filter_queries.genre %}checked{% endif %}>
                  {{ genre.name }}
                  ({{ filter_counts.genre|get_item:genre.slug|get_item:'count' }})
                </label>
                {% if genre.has_sub_genre %}
                  <div class="sub-filters">
                    {% for sub_genre in genres %}
                      {% if sub_genre.parent == genre %}
                        {% if filter_counts.genre|get_item:genre.slug|get_item:'sub_items'|get_item:sub_genre.slug > 0 %}
                          <label>
                            <input type="radio" name="genre" value="{{ sub_genre.slug }}" {% if sub_genre.slug == filter_queries.genre %}checked{% endif %}>
                            {{ sub_genre.name }}
                            ({{ filter_counts.genre|get_item:genre.slug|get_item:'sub_items'|get_item:sub_genre.slug }})
                          </label>
                        {% endif %}
                      {% endif %}
                    {% endfor %}
                  </div>{# / Sub genre #}
                {% endif %}
              </div>{# / Parent genre #}
            {% endif %}
          {% endif %}
        {% endfor %}
      </dd>
    </div>
    {% if status.slug != 'wishlist' %}
      <div>
        <dt>Formats</dt>
        <dd>
          <div>
            <label>
              <input type="radio" name="format" value="all" {% if filter_queries.format == 'all' %}checked{% endif %}>
              All
            </label>
          </div>
          {% for format in formats %}
            {% if filter_counts.format|get_item:format.slug > 0 %}
              <div>
                <label>
                  <input type="radio" name="format" value="{{ format.slug }}" {% if format.slug == filter_queries.format %}checked{% endif %}>
                  {{ format.name }}
                  ({{ filter_counts.format|get_item:format.slug }})
                </label>
              </div>
            {% endif %}
          {% endfor %}
        </dd>
      </div>
      <div>
        <dt>Locations</dt>
        <dd>
          <div>
            <label>
              <input type="radio" name="location" value="all" {% if filter_queries.location == 'all' %}checked{% endif %}>
              All
            </label>
          </div>
          {% for location in locations %}
            {% if filter_counts.location|get_item:location.slug > 0 %}
              <div>
                <label>
                  <input type="radio" name="location" value="{{ location.slug }}" {% if location.slug in filter_queries.location %}checked{% endif %}>
                  {{ location.name }}
                  ({{ filter_counts.location|get_item:location.slug }})
                </label>
              </div>
            {% endif %}
          {% endfor %}
        </dd>
      </div>
    {% endif %}
  </dl>
</form>

templates/components/book-list-item.html
{% load smartypants %}
<div class="cover">
  <a href="{{ book.get_absolute_url }}">
    {% if book.covers.all %}
      {% with book.covers.all|first as cover %}
        {% if cover.thumbnail %}
          <img loading="lazy" src="{{ cover.thumbnail.url }}"
            alt="{{ cover }}"
            height="{{ cover.thumbnail_height }}"
            width="{{ cover.thumbnail_width }}"
            title="{{ book }}">
        {% else %}
          {% include "components/no-cover.html" with class="incomplete" %}
        {% endif %}
      {% endwith %}
    {% else %}
      {% include "components/no-cover.html" %}
    {% endif %}
  </a>
</div>

<div class="title" title="{{ book }}">{{ book|smartypants }}</div>

templates/components/htmx-indicator.html
<div role="status" class="{% if wrapper_class %}{{ wrapper_class }} {% endif %} htmx-indicator">
  {# https://flowbite.com/docs/components/spinner/ #}
  <svg aria-hidden="true"
       class="animate-spin"
       viewBox="0 0 100 101"
       fill="none"
       xmlns="http://www.w3.org/2000/svg" width="28" height="28">
    <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
    <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
  </svg>
  <span class="sr-only">Loading...</span>
</div>

templates/components/logbook-list-item.html
{% with cover=book.covers.all|first %}
  <div class="cover">
    {% if cover.thumbnail %}
      <img src="{{ cover.thumbnail.url }}" alt="{{ cover }}" height="{{ cover.thumbnail_height }}" width="{{ cover.thumbnail_width }}">
    {% else %}
      {% include "components/no-cover.html" %}
    {% endif %}
  </div>
{% endwith %}

templates/components/logbook-list.html
{% load get_book status_display %}

<div
  id="logbook-list"
  hx-target="this"
  hx-ext="alpine-morph"
  hx-swap="morph"
  hx-push-url="true"
  x-data="{
    topOfList() {
      document.getElementById('logbook-list').scrollIntoView({ behavior: 'smooth' });
    },
  }">
  {% for log in page_obj %}
    <article>
      <header title="{{ log.log_timestamp }}" x-data="{ timestamp: false }" @click="timestamp = !timestamp">
        <span x-show="!timestamp">{{ log.log_timestamp|timesince }} <span class="subdued">ago</span></span>
        <span x-show="timestamp" x-cloak>{{ log.log_timestamp|date:"l, F j, Y, g:i A" }}</span>
      </header>
      <div class="change-body">
        {% if log.log_type == 'book' %}
          {% with book=books|get_book:log.id %}
            {% if book %}
              <a href="{% url 'book_detail' book.id %}">
                {% include "components/logbook-list-item.html" %}
                <div class="change-details">
                  <div class="title">{{ book }}</div>
                  <div class="change">Added <span class="subdued">→</span> {{ log.original_status|status_display }}</div>
                </div>
              </a>
            {% endif %}
          {% endwith %}
        {% elif log.log_type == 'status_change' %}
          {% with book=books|get_book:log.book_id %}
            {% if book %}
              <a href="{% url 'book_detail' book.id %}">
                {% include "components/logbook-list-item.html" %}
                <div class="change-details">
                  <div class="title">{{ book.title }}</div>
                  <div class="change">{{ log.old_status|status_display }} <span class="subdued">→</span> {{ log.new_status|status_display }}</div>
                </div>
              </a>
            {% endif %}
          {% endwith %}
        {% endif %}
      </div>
    </article>
  {% endfor %}
  {% if page_obj.has_other_pages %}
    <div class="pagination">
      {% if page_obj.has_previous %}
        <form method="get"
          action="{% url 'logbook' %}"
          hx-get="{% url 'logbook' %}"
          @htmx:after-request="topOfList"
          x-data="{ loading: false }">
          <input type="hidden" name="page" value="{{ page_obj.previous_page_number }}">
          <button :class="loading ? 'loading' : ''" @click="loading = true" x-on:htmx:after-swap.window="loading = false">Previous</button>
        </form>
      {% else %}
        <button disabled>Previous</button>
      {% endif %}
      <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
      {% if page_obj.has_next %}
        <form method="get"
          action="{% url 'logbook' %}"
          hx-get="{% url 'logbook' %}"
          @htmx:after-request="topOfList"
          x-data="{ loading: false }">
          <input type="hidden" name="page" value="{{ page_obj.next_page_number }}">
          <button :class="loading ? 'loading' : ''" @click="loading = true" x-on:htmx:after-swap.window="loading = false">Next</button>
        </form>
      {% else %}
        <button disabled>Next</button>
      {% endif %}
    </div>
  {% endif %}
</div>

templates/components/messages.html
<div class="messages">
  <ul>
    {% for message in messages %}
      <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
</div>

templates/components/no-cover.html
<div class="no-cover{% if class %} {{ class }}{% endif %}">
  {# https://remixicon.com/icon/book-line #}
  <svg class="book" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M3 18.5V5C3 3.34315 4.34315 2 6 2H20C20.5523 2 21 2.44772 21 3V21C21 21.5523 20.5523 22 20 22H6.5C4.567 22 3 20.433 3 18.5ZM19 20V17H6.5C5.67157 17 5 17.6716 5 18.5C5 19.3284 5.67157 20 6.5 20H19ZM5 15.3368C5.45463 15.1208 5.9632 15 6.5 15H19V4H6C5.44772 4 5 4.44772 5 5V15.3368Z"></path></svg>
</div>

templates/components/ol-search-form.html
<form method="get"
  action="{% url 'open_library_search' %}"
  id="openLibraryForm"
  x-data="{
    loading: false,
    query: '{{ query|escapejs }}',
    everything: {% if form.everything.value == None or form.everything.value == '' %}false{% else %}true{% endif %},
    fieldEverything: document.getElementById('id_everything'),
    fieldTitle: document.getElementById('id_title'),
    toggleFields() {
      this.everything = !this.everything;
      this.$nextTick(() => {
        const inputToFocus = (this.everything) ? this.fieldEverything : this.fieldTitle;
        if (inputToFocus) {
          setTimeout(() => {
            inputToFocus.focus();
          }, 25);
        }
      });
    }
  }"
  x-init="
    $nextTick(() => {
      if (query) {
        document.getElementById('id_title').value = query;
      }
    })
  "
  @submit="loading = true">
  <fieldset>
    {% for field in form %}
      <span
        {% if field.html_name == 'everything' %}x-show="everything"{% endif %}
        {% if field.html_name != 'everything' %}x-show="!everything"{% endif %}
      >
        {{ field.as_field_group }}
      </span>
    {% endfor %}

    <button x-cloak class="link toggle" type="button" @click="toggleFields">
      …or search <span x-show="!everything">all fields</span> <span x-show="everything">Title and Author</span>
    </button>

    <label for="id_status">Status</label>
    <select name="status" id="id_status">
      {% for x, y in status_choices %}
        <option value="{{ x }}"{% if status and status.slug == x %} selected{% endif %}>{{ y }}</option>
      {% endfor %}
    </select>
  </fieldset>
  <button :class="loading ? 'loading' : ''" type="submit">Search Open Library</button>
</form>

templates/components/search-form.html
<div class="search-form">
  <form action="{% url 'search' %}" method="get">
    <input type="search" name="q" placeholder="Search your collection" value="{{ query }}">
  </form>
</div>

templates/components/status-nav.html
{% load get_item %}

<nav class="status mb-10">
  <ol>
    {% for s in statuses %}
      <li{% if s.0 == status.slug %} class="active"{% endif %}>
        <a href="{% url 'status' status=s.0 %}"{% if s.0 == status.slug %} aria-current="page"{% endif %}>
          {{ s.1 }}
          {% if status_counts|get_item:s.0 != None %}<small>({{ status_counts|get_item:s.0 }})</small>{% endif %}
        </a>
      </li>
    {% endfor %}
  </ol>
</nav>